name: Update Markdown Files

on:
  schedule:
    # Runs every 1 minute
    - cron: "*/1 * * * *"

jobs:
  update-md-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List .md files
      run: |
        echo "Listing .md files:"
        find . -name "*.md"

    - name: Update .md files
      run: |
        # Append "-" to the end of each .md file's content
        for file in $(find . -name "*.md"); do
          echo "Appending '-' to $file"
          echo "-" >> "$file"
        done

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "folilinsheeerter@outlook.com"
        git config --global user.name "PascalTraits"
        git add .
        git commit -m "Automated update: appended '-' to .md files" || echo "No changes to commit"
        git push
