name: Update Specific Markdown Files

on:
  schedule:
    # Runs every 1 minute
    - cron: "*/1 * * * *"

jobs:
  update-md-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - List current directory
      run: ls -alh

    - name: Debug - Check for .md files
      run: find . -name "*.md"

    - name: Debug - Show contents of specific .md files before update
      run: |
        files=(
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android-and-Pocket-Edition/README.md"
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android/Download Minecraft (MOD, Immortality) 1.21.2.02 APK.md"
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android/Minecraft-Apk-Download-v1.21.20.23-Free-Android-and-pocket-edition.md"
        )
        for file in "${files[@]}"; do
          if [ -f "$file" ]; then
            echo "Contents of $file before update:"
            cat "$file"
          else
            echo "$file does not exist"
          fi
        done

    - name: Update specific .md files
      run: |
        files=(
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android-and-Pocket-Edition/README.md"
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android/Download Minecraft (MOD, Immortality) 1.21.2.02 APK.md"
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android/Minecraft-Apk-Download-v1.21.20.23-Free-Android-and-pocket-edition.md"
        )
        for file in "${files[@]}"; do
          if [ -f "$file" ]; then
            echo "Appending '-' to $file"
            echo "-" >> "$file"
          else
            echo "$file does not exist"
          fi
        done

    - name: Debug - Show contents of specific .md files after update
      run: |
        files=(
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android-and-Pocket-Edition/README.md"
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android/Download Minecraft (MOD, Immortality) 1.21.2.02 APK.md"
          "Minecraft-Apk-Download-v1.21.20.23-Free-Android/Minecraft-Apk-Download-v1.21.20.23-Free-Android-and-pocket-edition.md"
        )
        for file in "${files[@]}"; do
          if [ -f "$file" ]; then
            echo "Contents of $file after update:"
            cat "$file"
          else
            echo "$file does not exist"
          fi
        done

    - name: Debug - Show changes
      run: git diff

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "folilinsheeerter@outlook.com"
        git config --global user.name "PascalTraits"
        git add .
        git commit -m "Automated update: appended '-' to specific .md files" || echo "No changes to commit"
        git push
